#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoyaliEller
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BoyaliEllerDB")]
	public partial class linkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKullaniciGiri(KullaniciGiri instance);
    partial void UpdateKullaniciGiri(KullaniciGiri instance);
    partial void DeleteKullaniciGiri(KullaniciGiri instance);
    partial void InsertVeliler(Veliler instance);
    partial void UpdateVeliler(Veliler instance);
    partial void DeleteVeliler(Veliler instance);
    partial void InsertOgrenciler(Ogrenciler instance);
    partial void UpdateOgrenciler(Ogrenciler instance);
    partial void DeleteOgrenciler(Ogrenciler instance);
    partial void InsertOgretmenler(Ogretmenler instance);
    partial void UpdateOgretmenler(Ogretmenler instance);
    partial void DeleteOgretmenler(Ogretmenler instance);
    #endregion
		
		public linkDataContext() : 
				base(global::BoyaliEller.Properties.Settings.Default.BoyaliEllerDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KullaniciGiri> KullaniciGiris
		{
			get
			{
				return this.GetTable<KullaniciGiri>();
			}
		}
		
		public System.Data.Linq.Table<Veliler> Velilers
		{
			get
			{
				return this.GetTable<Veliler>();
			}
		}
		
		public System.Data.Linq.Table<Ogrenciler> Ogrencilers
		{
			get
			{
				return this.GetTable<Ogrenciler>();
			}
		}
		
		public System.Data.Linq.Table<Ogretmenler> Ogretmenlers
		{
			get
			{
				return this.GetTable<Ogretmenler>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KullaniciGiris")]
	public partial class KullaniciGiri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KullaniciAdi;
		
		private string _KullaniciSifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKullaniciAdiChanging(string value);
    partial void OnKullaniciAdiChanged();
    partial void OnKullaniciSifreChanging(string value);
    partial void OnKullaniciSifreChanged();
    #endregion
		
		public KullaniciGiri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciAdi", DbType="NVarChar(50)")]
		public string KullaniciAdi
		{
			get
			{
				return this._KullaniciAdi;
			}
			set
			{
				if ((this._KullaniciAdi != value))
				{
					this.OnKullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._KullaniciAdi = value;
					this.SendPropertyChanged("KullaniciAdi");
					this.OnKullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KullaniciSifre", DbType="NVarChar(15)")]
		public string KullaniciSifre
		{
			get
			{
				return this._KullaniciSifre;
			}
			set
			{
				if ((this._KullaniciSifre != value))
				{
					this.OnKullaniciSifreChanging(value);
					this.SendPropertyChanging();
					this._KullaniciSifre = value;
					this.SendPropertyChanged("KullaniciSifre");
					this.OnKullaniciSifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Veliler")]
	public partial class Veliler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VeliID;
		
		private string _VeliAdi;
		
		private string _VeliSoyadi;
		
		private string _VeliTelefon;
		
		private string _VeliAdres;
		
		private string _VeliTC;
		
		private EntitySet<Ogrenciler> _Ogrencilers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVeliIDChanging(int value);
    partial void OnVeliIDChanged();
    partial void OnVeliAdiChanging(string value);
    partial void OnVeliAdiChanged();
    partial void OnVeliSoyadiChanging(string value);
    partial void OnVeliSoyadiChanged();
    partial void OnVeliTelefonChanging(string value);
    partial void OnVeliTelefonChanged();
    partial void OnVeliAdresChanging(string value);
    partial void OnVeliAdresChanged();
    partial void OnVeliTCChanging(string value);
    partial void OnVeliTCChanged();
    #endregion
		
		public Veliler()
		{
			this._Ogrencilers = new EntitySet<Ogrenciler>(new Action<Ogrenciler>(this.attach_Ogrencilers), new Action<Ogrenciler>(this.detach_Ogrencilers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VeliID
		{
			get
			{
				return this._VeliID;
			}
			set
			{
				if ((this._VeliID != value))
				{
					this.OnVeliIDChanging(value);
					this.SendPropertyChanging();
					this._VeliID = value;
					this.SendPropertyChanged("VeliID");
					this.OnVeliIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliAdi", DbType="NVarChar(50)")]
		public string VeliAdi
		{
			get
			{
				return this._VeliAdi;
			}
			set
			{
				if ((this._VeliAdi != value))
				{
					this.OnVeliAdiChanging(value);
					this.SendPropertyChanging();
					this._VeliAdi = value;
					this.SendPropertyChanged("VeliAdi");
					this.OnVeliAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliSoyadi", DbType="NVarChar(50)")]
		public string VeliSoyadi
		{
			get
			{
				return this._VeliSoyadi;
			}
			set
			{
				if ((this._VeliSoyadi != value))
				{
					this.OnVeliSoyadiChanging(value);
					this.SendPropertyChanging();
					this._VeliSoyadi = value;
					this.SendPropertyChanged("VeliSoyadi");
					this.OnVeliSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliTelefon", DbType="NVarChar(11)")]
		public string VeliTelefon
		{
			get
			{
				return this._VeliTelefon;
			}
			set
			{
				if ((this._VeliTelefon != value))
				{
					this.OnVeliTelefonChanging(value);
					this.SendPropertyChanging();
					this._VeliTelefon = value;
					this.SendPropertyChanged("VeliTelefon");
					this.OnVeliTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliAdres", DbType="NVarChar(300)")]
		public string VeliAdres
		{
			get
			{
				return this._VeliAdres;
			}
			set
			{
				if ((this._VeliAdres != value))
				{
					this.OnVeliAdresChanging(value);
					this.SendPropertyChanging();
					this._VeliAdres = value;
					this.SendPropertyChanged("VeliAdres");
					this.OnVeliAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliTC", DbType="NVarChar(11)")]
		public string VeliTC
		{
			get
			{
				return this._VeliTC;
			}
			set
			{
				if ((this._VeliTC != value))
				{
					this.OnVeliTCChanging(value);
					this.SendPropertyChanging();
					this._VeliTC = value;
					this.SendPropertyChanged("VeliTC");
					this.OnVeliTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veliler_Ogrenciler", Storage="_Ogrencilers", ThisKey="VeliID", OtherKey="VeliID")]
		public EntitySet<Ogrenciler> Ogrencilers
		{
			get
			{
				return this._Ogrencilers;
			}
			set
			{
				this._Ogrencilers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ogrencilers(Ogrenciler entity)
		{
			this.SendPropertyChanging();
			entity.Veliler = this;
		}
		
		private void detach_Ogrencilers(Ogrenciler entity)
		{
			this.SendPropertyChanging();
			entity.Veliler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogrenciler")]
	public partial class Ogrenciler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OgrenciID;
		
		private string _OgrenciAdi;
		
		private string _OgrenciSoyadi;
		
		private System.Nullable<int> _OgrenciYasi;
		
		private string _OgrenciCinsiyet;
		
		private string _OgrenciTC;
		
		private string _OgrenciAdres;
		
		private System.Nullable<int> _VeliID;
		
		private System.Nullable<int> _OgretmenID;
		
		private EntityRef<Ogretmenler> _Ogretmenler;
		
		private EntityRef<Veliler> _Veliler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOgrenciIDChanging(int value);
    partial void OnOgrenciIDChanged();
    partial void OnOgrenciAdiChanging(string value);
    partial void OnOgrenciAdiChanged();
    partial void OnOgrenciSoyadiChanging(string value);
    partial void OnOgrenciSoyadiChanged();
    partial void OnOgrenciYasiChanging(System.Nullable<int> value);
    partial void OnOgrenciYasiChanged();
    partial void OnOgrenciCinsiyetChanging(string value);
    partial void OnOgrenciCinsiyetChanged();
    partial void OnOgrenciTCChanging(string value);
    partial void OnOgrenciTCChanged();
    partial void OnOgrenciAdresChanging(string value);
    partial void OnOgrenciAdresChanged();
    partial void OnVeliIDChanging(System.Nullable<int> value);
    partial void OnVeliIDChanged();
    partial void OnOgretmenIDChanging(System.Nullable<int> value);
    partial void OnOgretmenIDChanged();
    #endregion
		
		public Ogrenciler()
		{
			this._Ogretmenler = default(EntityRef<Ogretmenler>);
			this._Veliler = default(EntityRef<Veliler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OgrenciID
		{
			get
			{
				return this._OgrenciID;
			}
			set
			{
				if ((this._OgrenciID != value))
				{
					this.OnOgrenciIDChanging(value);
					this.SendPropertyChanging();
					this._OgrenciID = value;
					this.SendPropertyChanged("OgrenciID");
					this.OnOgrenciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciAdi", DbType="NVarChar(50)")]
		public string OgrenciAdi
		{
			get
			{
				return this._OgrenciAdi;
			}
			set
			{
				if ((this._OgrenciAdi != value))
				{
					this.OnOgrenciAdiChanging(value);
					this.SendPropertyChanging();
					this._OgrenciAdi = value;
					this.SendPropertyChanged("OgrenciAdi");
					this.OnOgrenciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciSoyadi", DbType="NVarChar(50)")]
		public string OgrenciSoyadi
		{
			get
			{
				return this._OgrenciSoyadi;
			}
			set
			{
				if ((this._OgrenciSoyadi != value))
				{
					this.OnOgrenciSoyadiChanging(value);
					this.SendPropertyChanging();
					this._OgrenciSoyadi = value;
					this.SendPropertyChanged("OgrenciSoyadi");
					this.OnOgrenciSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciYasi", DbType="Int")]
		public System.Nullable<int> OgrenciYasi
		{
			get
			{
				return this._OgrenciYasi;
			}
			set
			{
				if ((this._OgrenciYasi != value))
				{
					this.OnOgrenciYasiChanging(value);
					this.SendPropertyChanging();
					this._OgrenciYasi = value;
					this.SendPropertyChanged("OgrenciYasi");
					this.OnOgrenciYasiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciCinsiyet", DbType="NVarChar(5)")]
		public string OgrenciCinsiyet
		{
			get
			{
				return this._OgrenciCinsiyet;
			}
			set
			{
				if ((this._OgrenciCinsiyet != value))
				{
					this.OnOgrenciCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._OgrenciCinsiyet = value;
					this.SendPropertyChanged("OgrenciCinsiyet");
					this.OnOgrenciCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciTC", DbType="NVarChar(11)")]
		public string OgrenciTC
		{
			get
			{
				return this._OgrenciTC;
			}
			set
			{
				if ((this._OgrenciTC != value))
				{
					this.OnOgrenciTCChanging(value);
					this.SendPropertyChanging();
					this._OgrenciTC = value;
					this.SendPropertyChanged("OgrenciTC");
					this.OnOgrenciTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgrenciAdres", DbType="NVarChar(300)")]
		public string OgrenciAdres
		{
			get
			{
				return this._OgrenciAdres;
			}
			set
			{
				if ((this._OgrenciAdres != value))
				{
					this.OnOgrenciAdresChanging(value);
					this.SendPropertyChanging();
					this._OgrenciAdres = value;
					this.SendPropertyChanged("OgrenciAdres");
					this.OnOgrenciAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VeliID", DbType="Int")]
		public System.Nullable<int> VeliID
		{
			get
			{
				return this._VeliID;
			}
			set
			{
				if ((this._VeliID != value))
				{
					if (this._Veliler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVeliIDChanging(value);
					this.SendPropertyChanging();
					this._VeliID = value;
					this.SendPropertyChanged("VeliID");
					this.OnVeliIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenID", DbType="Int")]
		public System.Nullable<int> OgretmenID
		{
			get
			{
				return this._OgretmenID;
			}
			set
			{
				if ((this._OgretmenID != value))
				{
					if (this._Ogretmenler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOgretmenIDChanging(value);
					this.SendPropertyChanging();
					this._OgretmenID = value;
					this.SendPropertyChanged("OgretmenID");
					this.OnOgretmenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ogretmenler_Ogrenciler", Storage="_Ogretmenler", ThisKey="OgretmenID", OtherKey="OgretmenID", IsForeignKey=true)]
		public Ogretmenler Ogretmenler
		{
			get
			{
				return this._Ogretmenler.Entity;
			}
			set
			{
				Ogretmenler previousValue = this._Ogretmenler.Entity;
				if (((previousValue != value) 
							|| (this._Ogretmenler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ogretmenler.Entity = null;
						previousValue.Ogrencilers.Remove(this);
					}
					this._Ogretmenler.Entity = value;
					if ((value != null))
					{
						value.Ogrencilers.Add(this);
						this._OgretmenID = value.OgretmenID;
					}
					else
					{
						this._OgretmenID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ogretmenler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Veliler_Ogrenciler", Storage="_Veliler", ThisKey="VeliID", OtherKey="VeliID", IsForeignKey=true)]
		public Veliler Veliler
		{
			get
			{
				return this._Veliler.Entity;
			}
			set
			{
				Veliler previousValue = this._Veliler.Entity;
				if (((previousValue != value) 
							|| (this._Veliler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Veliler.Entity = null;
						previousValue.Ogrencilers.Remove(this);
					}
					this._Veliler.Entity = value;
					if ((value != null))
					{
						value.Ogrencilers.Add(this);
						this._VeliID = value.VeliID;
					}
					else
					{
						this._VeliID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Veliler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ogretmenler")]
	public partial class Ogretmenler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OgretmenID;
		
		private string _OgretmenAdi;
		
		private string _OgretmenSoyadi;
		
		private string _OgretmenCinsiyet;
		
		private string _OgretmenTelefon;
		
		private string _OgretmenAdres;
		
		private string _OgretmenTC;
		
		private System.Nullable<int> _OgretmenMaas;
		
		private EntitySet<Ogrenciler> _Ogrencilers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOgretmenIDChanging(int value);
    partial void OnOgretmenIDChanged();
    partial void OnOgretmenAdiChanging(string value);
    partial void OnOgretmenAdiChanged();
    partial void OnOgretmenSoyadiChanging(string value);
    partial void OnOgretmenSoyadiChanged();
    partial void OnOgretmenCinsiyetChanging(string value);
    partial void OnOgretmenCinsiyetChanged();
    partial void OnOgretmenTelefonChanging(string value);
    partial void OnOgretmenTelefonChanged();
    partial void OnOgretmenAdresChanging(string value);
    partial void OnOgretmenAdresChanged();
    partial void OnOgretmenTCChanging(string value);
    partial void OnOgretmenTCChanged();
    partial void OnOgretmenMaasChanging(System.Nullable<int> value);
    partial void OnOgretmenMaasChanged();
    #endregion
		
		public Ogretmenler()
		{
			this._Ogrencilers = new EntitySet<Ogrenciler>(new Action<Ogrenciler>(this.attach_Ogrencilers), new Action<Ogrenciler>(this.detach_Ogrencilers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OgretmenID
		{
			get
			{
				return this._OgretmenID;
			}
			set
			{
				if ((this._OgretmenID != value))
				{
					this.OnOgretmenIDChanging(value);
					this.SendPropertyChanging();
					this._OgretmenID = value;
					this.SendPropertyChanged("OgretmenID");
					this.OnOgretmenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenAdi", DbType="NVarChar(50)")]
		public string OgretmenAdi
		{
			get
			{
				return this._OgretmenAdi;
			}
			set
			{
				if ((this._OgretmenAdi != value))
				{
					this.OnOgretmenAdiChanging(value);
					this.SendPropertyChanging();
					this._OgretmenAdi = value;
					this.SendPropertyChanged("OgretmenAdi");
					this.OnOgretmenAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenSoyadi", DbType="NVarChar(50)")]
		public string OgretmenSoyadi
		{
			get
			{
				return this._OgretmenSoyadi;
			}
			set
			{
				if ((this._OgretmenSoyadi != value))
				{
					this.OnOgretmenSoyadiChanging(value);
					this.SendPropertyChanging();
					this._OgretmenSoyadi = value;
					this.SendPropertyChanged("OgretmenSoyadi");
					this.OnOgretmenSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenCinsiyet", DbType="NVarChar(5)")]
		public string OgretmenCinsiyet
		{
			get
			{
				return this._OgretmenCinsiyet;
			}
			set
			{
				if ((this._OgretmenCinsiyet != value))
				{
					this.OnOgretmenCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._OgretmenCinsiyet = value;
					this.SendPropertyChanged("OgretmenCinsiyet");
					this.OnOgretmenCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenTelefon", DbType="NVarChar(11)")]
		public string OgretmenTelefon
		{
			get
			{
				return this._OgretmenTelefon;
			}
			set
			{
				if ((this._OgretmenTelefon != value))
				{
					this.OnOgretmenTelefonChanging(value);
					this.SendPropertyChanging();
					this._OgretmenTelefon = value;
					this.SendPropertyChanged("OgretmenTelefon");
					this.OnOgretmenTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenAdres", DbType="NVarChar(300)")]
		public string OgretmenAdres
		{
			get
			{
				return this._OgretmenAdres;
			}
			set
			{
				if ((this._OgretmenAdres != value))
				{
					this.OnOgretmenAdresChanging(value);
					this.SendPropertyChanging();
					this._OgretmenAdres = value;
					this.SendPropertyChanged("OgretmenAdres");
					this.OnOgretmenAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenTC", DbType="NVarChar(11)")]
		public string OgretmenTC
		{
			get
			{
				return this._OgretmenTC;
			}
			set
			{
				if ((this._OgretmenTC != value))
				{
					this.OnOgretmenTCChanging(value);
					this.SendPropertyChanging();
					this._OgretmenTC = value;
					this.SendPropertyChanged("OgretmenTC");
					this.OnOgretmenTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OgretmenMaas", DbType="Int")]
		public System.Nullable<int> OgretmenMaas
		{
			get
			{
				return this._OgretmenMaas;
			}
			set
			{
				if ((this._OgretmenMaas != value))
				{
					this.OnOgretmenMaasChanging(value);
					this.SendPropertyChanging();
					this._OgretmenMaas = value;
					this.SendPropertyChanged("OgretmenMaas");
					this.OnOgretmenMaasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ogretmenler_Ogrenciler", Storage="_Ogrencilers", ThisKey="OgretmenID", OtherKey="OgretmenID")]
		public EntitySet<Ogrenciler> Ogrencilers
		{
			get
			{
				return this._Ogrencilers;
			}
			set
			{
				this._Ogrencilers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ogrencilers(Ogrenciler entity)
		{
			this.SendPropertyChanging();
			entity.Ogretmenler = this;
		}
		
		private void detach_Ogrencilers(Ogrenciler entity)
		{
			this.SendPropertyChanging();
			entity.Ogretmenler = null;
		}
	}
}
#pragma warning restore 1591
